version: '3.9'
services:
  app:
    build:
      context: .
      target: dev
    working_dir: /app
    ports:
      - 3005:3000
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ./:/app
      - bundlerCached:/usr/local/bundle
      - yarnCached:/usr/local/share/.cache/yarn/v6
      - nodeModulesCached:/app/node_modules

volumes:
  bundlerCached:
  yarnCached:
  nodeModulesCached:
